import js from '@eslint/js';
import globals from 'globals';

export default [
  js.configs.recommended,
  {
    files: ['js/**/*.js', 'config/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'script',
      globals: {
        // browser globals (window, document, localStorage, etc.)
        ...globals.browser,

        // CDN Libs
        jsPDF: 'readonly',
        JSZip: 'readonly',
        Viz: 'readonly',
        ReportI18n: 'readonly',
        // globals.js
        ASSESSMENT_CONFIG: 'writable',
        INITIAL_VERSION: 'readonly',
        getTodayISO: 'readonly',
        todayISO: 'writable',
        DEFAULT_DAMAGE_SCENARIOS: 'writable',
        PROBABILITY_CRITERIA: 'writable',
        RISK_THRESHOLDS: 'writable',
        RISK_UNKNOWN: 'writable',
        VALID_IMPACT_VALUES: 'writable',
        IMPACT_LABELS: 'writable',
        IMPACT_CSS_CLASSES: 'writable',
        SEVERITY_LEVEL_FACTORS: 'writable',
        PROTECTION_LEVEL_WEIGHTS: 'writable',
        PROTECTION_LEVEL_RANKING: 'writable',
        syncGlobalsFromAssessmentConfig: 'readonly',
        analysisData: 'writable',
        activeAnalysisId: 'writable',
        createDefaultAnalysis: 'readonly',
        // utils.js
        getActiveAnalysis: 'readonly',
        computeRiskScore: 'readonly',
        getRiskMeta: 'readonly',
        getRiskClass: 'readonly',
        getRiskCssClass: 'readonly',
        generateUID: 'readonly',
        saveAnalyses: 'readonly',
        loadAnalyses: 'readonly',
        getDisplayDamageScenarios: 'readonly',
        getAllDamageScenarioIds: 'readonly',
        escapeHtml: 'readonly',
        showToast: 'readonly',
        showConfirmation: 'readonly',
        getLocalizedField: 'readonly',
        setLocalizedField: 'readonly',
        // i18n / prefs
        i18n: 'readonly',
        t: 'readonly',
        tRiskLabel: 'readonly',
        currentLang: 'writable',
        userPrefs: 'writable',
        TaraPrefs: 'readonly',
        // analysis_core.js
        activateAnalysis: 'readonly',
        deleteActiveAnalysis: 'readonly',
        exportAnalysis: 'readonly',
        migrateAnalysis: 'readonly',
        fillAnalysisForm: 'readonly',
        prepareNewAnalysisModal: 'readonly',
        renderAnalysisSelector: 'readonly',
        renderOverview: 'readonly',
        initAnalysisCoreListeners: 'readonly',
        saveCurrentAnalysisState: 'readonly',
        renderActiveTab: 'readonly',
        // modules/
        renderAssets: 'readonly',
        renderDamageScenarios: 'readonly',
        renderImpactMatrix: 'readonly',
        renderRiskAnalysis: 'readonly',
        renderSecurityGoals: 'readonly',
        renderHistoryTable: 'readonly',
        purgeDamageScenarioFromRiskEntries: 'readonly',
        sanitizeEntryDsReferences: 'readonly',
        reindexRiskIDs: 'readonly',
        // attack_tree/
        openAttackTreeModal: 'readonly',
        generateDotString: 'readonly',
        generateResidualRiskDotString: 'readonly',
        populateAttackTreeDropdowns: 'readonly',
        initAttackTreeImpactAdders: 'readonly',
        initAttackTreeImpactRemovers: 'readonly',
        initAttackTreeLeafRemovers: 'readonly',
        updateAttackTreeKSTUSummariesFromForm: 'readonly',
        applyWorstCaseInheritance: 'readonly',
        applyImpactInheritance: 'readonly',
        rebuildTreeRiskLevelsFromConfig: 'readonly',
        generateNextRiskID: 'readonly',
        _computeRiskScore: 'readonly',
        _getRiskCssClass: 'readonly',
        _getTreeDepthForData: 'readonly',
        _renderNodeSummaryHTML: 'readonly',
        // residual_risk/
        renderResidualRisk: 'readonly',
        ensureResidualRiskSynced: 'readonly',
        syncResidualRiskFromRiskAnalysis: 'readonly',
        computeResidualTreeMetrics: 'readonly',
        rrIterateLeaves: 'readonly',
        rrLegacyKey: 'readonly',
        // report/
        generateReportPdf: 'readonly',
        // config_loader.js
        onAssessmentConfigReloaded: 'readonly',
        promptReloadAssessmentConfig: 'readonly',
        reloadAssessmentConfigFromJsonText: 'readonly',
      },
    },
    rules: {
      'no-undef': 'error',
      'no-dupe-keys': 'error',
      'no-duplicate-case': 'error',
      'no-unreachable': 'error',
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
      'no-redeclare': 'off',
      'no-empty': 'off',
      // Pre-existing issues in codebase – warn only, fix in dedicated stories
      'no-useless-assignment': 'warn',
      'no-useless-escape': 'warn',
      // Formatting handled by Prettier
      indent: 'off',
      quotes: 'off',
      semi: 'off',
      'comma-dangle': 'off',
      'max-len': 'off',
    },
  },
];
